export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL';

export const SET_PRODUCTS_TOTAL_ITEM_COUNT = 'SET_PRODUCTS_TOTAL_ITEM_COUNT';

export const SET_TAG_STATE = 'SET_TAG_STATE';
export const SET_TAG_STATE_FAIL = 'SET_TAG_STATE_FAIL';
export const SET_TAG_STATE_SUCCESS = 'SET_TAG_STATE_SUCCESS';

export const ADD_ITEM_BASKET = 'ADD_ITEM_BASKET';
